mysteries = {
    '1': {
        'id': '1',
        'description': "A woman - at work - is going downstairs, when suddenly there is a blackout. In that very moment she realizes that her husband is about to die.",
        'solution': "The woman worked as an electrician at a hospital and she knew that the emergency generators were broken. He husband had had a car crash and he was at that hospital, connected to a machine that kept him alive. When the blackout happened she knew that her husband couldn't be breathing by himself and therefore that he was dying.",
        'image_url': '/static/images/mystery1.jpg',
    },
    '2': {
        'id': '2',
        'description': "When Martin woke up that morning, he was surprised to see the door open. As soon as he crossed the threshold he got beheaded.",
        'solution': "Martin was a canary that had been living in his cage for four months. Silvester - a cat - was waiting for his opportumity to catch Martin and eat him. When their owner left the cage door open by mistake Martin flew out of it and Silvester bit off his small head.",
        'image_url': '/static/images/mystery2.jpg',
    },
    '3': {
        'id': '3',
        'description': "A woman buys a new pair of red high heels. Hours later, she dies.",
        'solution': "Her husband was a magician that was doing a gun trick with an apple on her head and his eyes closed. He didn't realize that she was wearing high heals so he didn't calculate the height accurately.... so he killed her.",
        'image_url': '/static/images/mystery3.jpg',
    },
    '4': {
        'id': '4',
        'description': "A man and his wife raced through the streets. They stopped, and the husband got out of the car. When he came back, his wife was dead, and there was a stranger in the car",
        'solution': "The wife was about to have a baby. They drove to the hospital. The husband left to get a wheelchair, but the baby was born in the meantime, and the wife didn't survive the birth.",
        'image_url': '/static/images/mystery4.jpg',
    },
    '5': {
        'id': '5',
        'description': "A hunter aimed his gun carefully and fired. Seconds later, he realized his mistake. Minutes later, he was dead.",
        'solution': "It was winter. He fired the gun near a snowy cliff, which started an avalanche.",
        'image_url': '/static/images/mystery5.jpg',
    },
    '6': {
        'id': '6',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery6.jpg',
    },
    '7': {
        'id': '7',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery7.jpg',
    },
    '8': {
        'id': '8',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery8.jpg',
    },
    '9': {
        'id': '9',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery9.jpg',
    },
    '10': {
        'id': '10',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery10.jpg',
    },
    '11': {
        'id': '11',
        'description': "A man is found hanging in an otherwise empty locked room with a puddle of water under his feet.",
        'solution': "He stood on a block of ice to hang himself. The block of ice slowly melted, causing him to hang in the air and die. ",
        'image_url': '/static/images/mystery11.jpg',
    },
    '12': {
        'id': '12',
        'description': "Two men enter a bar. They are served identical drinks. One lives; the other dies.",
        'solution': "The drinks contain poisoned ice cubes; one man drinks slowly, giving them time to melt, while the other drinks quickly and thus doesn't get much of the poison.",
        'image_url': '/static/images/mystery12.jpg',
    },
    '13': {
        'id': '13',
        'description': "A man is running along a corridor with a piece of paper in his hand. The lights flicker, and the man drops to his knees and cries out, 'Oh no!'",
        'solution': "The man is delivering a pardon for a prisoner sentenced to death by electrocution. The flicker of the lights indicates that the person to be pardoned has just been electrocuted and they can no longer save him.",
        'image_url': '/static/images/mystery13.jpg',
    },
    '14': {
        'id': '14',
        'description': "A man wakes up one night to get some water. He turns off the light and goes back to bed. The next morning he looks out the window, screams, and kills himself.",
        'solution': "The man is a lighthouse keeper. He wasn't quite awake when he got up in the night -- unwittingly, he had shut off the light in the lighthouse. During the night, a ship crashes on the rocks. When the man realized what he had done, he killed himself.",
        'image_url': '/static/images/mystery14.jpg',
    },
    '15': {
        'id': '15',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery15.jpg',
    },
    '16': {
        'id': '16',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery16.jpg',
    },
    '17': {
        'id': '17',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery17.jpg',
    },
    '18': {
        'id': '18',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery18.jpg',
    },
    '19': {
        'id': '19',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery19.jpg',
    },
    '20': {
        'id': '20',
        'description': "",
        'solution': "",
        'image_url': '/static/images/mystery20.jpg',
    }
}
